import Head from "next/head";
import PodcastList from "components/PodcastList";

export async function getStaticProps() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_BASE_API}/podcast`);
  const podcast = await res.json();
  return {
    props: { podcast },
  };
}

const Home = ({ podcast }) => (
  <>
    <Head>
      <title>Afripods Light Test - Podcasts</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <PodcastList podcasts={podcast} title="Available podcasts" />
  </>
);

export default Home;
